owner: playt-net
repo: uptime

sites:
  - name: PLAYT.net
    url: https://playt.net
  - name: Clash Paradise
    url: https://clashparadise.io
  # Tracking www. separately, so we can perform experiments and know when they failed
  - name: Clash Paradise (www)
    url: https://www.clashparadise.io
  - name: Database
    url: https://5473.staging.clashparadise.io/api/admin/status/database
    __dangerous__body_degraded_if_text_missing: "operational"
    __dangerous__body_down: "outage"
  - name: Database (proxy)
    url: https://5473.staging.clashparadise.io/api/admin/status/database-proxy
    __dangerous__body_degraded_if_text_missing: "operational"
    __dangerous__body_down: "outage"
  - name: Events
    url: https://5473.staging.clashparadise.io/api/admin/status/events
    __dangerous__body_degraded_if_text_missing: "operational"
    __dangerous__body_down: "outage"
  - name: Compute
    url: https://5473.staging.clashparadise.io/api/admin/status/compute
    __dangerous__body_degraded_if_text_missing: "operational"
    __dangerous__body_down: "outage"
  - name: Email (primary)
    url: https://5473.staging.clashparadise.io/api/admin/status/email_primary
    __dangerous__body_degraded_if_text_missing: "operational"
    __dangerous__body_down: "outage"
  - name: Email (secondary)
    url: https://5473.staging.clashparadise.io/api/admin/status/email_secondary
    __dangerous__body_degraded_if_text_missing: "operational"
    __dangerous__body_down: "outage"
  - name: Maintenance
    url: https://5473.staging.clashparadise.io/api/admin/status/maintenance
    __dangerous__body_degraded_if_text_missing: "operational"
  - name: Queues
    url: https://clashparadise.io/api/admin/status/queues
    __dangerous__body_degraded_if_text_missing: "true"
  - name: DLQ
    url: https://clashparadise.io/api/admin/status/dlq
    __dangerous__body_degraded_if_text_missing: "true"
  - name: DLQ (staging)
    url: https://staging.clashparadise.io/api/admin/status/dlq
    __dangerous__body_degraded_if_text_missing: "true"
  - name: Clash Paradise (staging)
    url: https://staging.clashparadise.io
  - name: Trinity Swap
    url: https://swap3.games.c.playt.net
  - name: Stack Jumper
    url: https://stackgame.games.c.playt.net
  - name: Desert Racer
    url: https://racer.games.c.playt.net
  - name: Cupcaker
    url: https://packager.games.c.playt.net
  - name: Birdie Ball
    url: https://minigolf.games.c.playt.net
  - name: Cube Machine
    url: https://mewtrix.games.c.playt.net
  - name: Beach Basher
    url: https://gembasher.games.c.playt.net
  - name: Cook Faster
    url: https://cooking.games.c.playt.net
  - name: Solitaire Jack
    url: https://cardgame.games.c.playt.net
  - name: Derby Classic
    url: https://camel-race.games.c.playt.net
  - name: Trinity Swap (staging)
    url: https://swap3.games.c.playt.net
  - name: Stack Jumper (staging)
    url: https://stackgame.games.staging.c.playt.net
  - name: Desert Racer (staging)
    url: https://racer.games.staging.c.playt.net
  - name: Cupcaker (staging)
    url: https://packager.games.staging.c.playt.net
  - name: Birdie Ball (staging)
    url: https://minigolf.games.staging.c.playt.net
  - name: Cube Machine (staging)
    url: https://mewtrix.games.staging.c.playt.net
  - name: Beach Basher (staging)
    url: https://gembasher.games.staging.c.playt.net
  - name: Cook Faster (staging)
    url: https://cooking.games.staging.c.playt.net
  - name: Solitaire Jack (staging)
    url: https://cardgame.games.staging.c.playt.net
  - name: Derby Classic (staging)
    url: https://camel-race.games.staging.c.playt.net
  - name: Test Asset
    url: https://cdy-staging-images.s3.fr-par.scw.cloud/6315c576a434b3c5d2a652cf/bannerKey

workflowSchedule:
  # check uptime every 5 minutes, except 1-3 utc (3-5 gmt+1)
  uptime: "*/5 4-12,16-23 * * *"
  
assignees:
  - boredland
  - phlgr

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.playt.net
  logoUrl: https://avatars.githubusercontent.com/u/81310488?s=200&v=4
  name: PLAYT.net Uptime Monitor
  theme: light
  favicon: https://status.playt.net/favicon.png
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
