owner: playt-net
repo: uptime

sites:
  - name: PLAYT.net
    url: https://playt.net
  - name: Clash Paradise
    url: https://clashparadise.io
  # Tracking www. separately, so we can perform experiments and know when they failed
  - name: Clash Paradise (www)
    url: https://www.clashparadise.io
  - name: Email (primary)
    url: https://4201.staging.clashparadise.io/api/status/email_primary
    __dangerous__body_degraded_if_text_missing: true
  - name: Database
    url: https://4201.staging.clashparadise.io/api/status/database
    __dangerous__body_degraded_if_text_missing: true
  - name: Email (secondary)
    url: https://4201.staging.clashparadise.io/api/status/email_secondary
    __dangerous__body_degraded_if_text_missing: true
  - name: Containers
    url: https://4201.staging.clashparadise.io/api/status/containers
    __dangerous__body_degraded_if_text_missing: true
  - name: Events
    url: https://4201.staging.clashparadise.io/api/status/events
    __dangerous__body_degraded_if_text_missing: true
  - name: Clash Paradise (staging)
    url: https://staging.clashparadise.io
  - name: Trinity Swap
    url: https://swap3.games.playt.net
  - name: Trinity Swap (staging)
    url: https://swap3.games.staging.playt.net
  - name: Stack Jumper
    url: https://stackgame.games.playt.net
  - name: Stack Jumper (staging)
    url: https://stackgame.games.staging.playt.net
  - name: Desert Racer
    url: https://racer.games.playt.net
  - name: Desert Racer (staging)
    url: https://racer.games.staging.playt.net
  - name: Cupcaker
    url: https://packager.games.playt.net
  - name: Cupcaker (staging)
    url: https://packager.games.staging.playt.net
  - name: Birdie Ball
    url: https://minigolf.games.playt.net
  - name: Birdie Ball (staging)
    url: https://minigolf.games.staging.playt.net
  - name: Cube Machine
    url: https://mewtrix.games.playt.net
  - name: Cube Machine (staging)
    url: https://mewtrix.games.staging.playt.net
  - name: Beach Basher
    url: https://gembasher.games.playt.net
  - name: Beach Basher (staging)
    url: https://gembasher.games.staging.playt.net
  - name: Cook Faster
    url: https://cooking.games.playt.net
  - name: Cook Faster (staging)
    url: https://cooking.games.staging.playt.net
  - name: Solitaire Jack
    url: https://cardgame.games.playt.net
  - name: Solitaire Jack (staging)
    url: https://cardgame.games.staging.playt.net
  - name: Derby Classic
    url: https://camel-race.games.playt.net
  - name: Derby Classic (staging)
    url: https://camel-race.games.staging.playt.net

workflowSchedule:
  # check uptime every 5 minutes, except 1-3 utc (3-5 gmt+1)
  uptime: "*/5 4-12,16-23 * * *"
  
assignees:
  - boredland
  - phlgr

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.playt.net
  logoUrl: https://avatars.githubusercontent.com/u/81310488?s=200&v=4
  name: PLAYT.net Uptime Monitor
  theme: light
  favicon: https://status.playt.net/favicon.png
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
